# General configuration
mode: "testing"  # production or testing
output_directory: "./output"

platform: # optional
  # Type of platform-specific handler
  # Options: generic, reddit, twitter, discord, custom
  type:   # facebook
  # Platform identifier (used in output data)
  platform: facebook
  # Path to Facebook data directory (contains message_1.json files)
  platform_data_path: /home/lewis/1project/Chat_data_preprocessing/data/downloaded_data/messages/inbox
  
  # Path for final processed output
  output_path: data/output/

  # Set your Facebook username to correctly identify your messages as "assistant"
  # (If not set, will try to identify automatically using heuristics)
  user_name: "大大力良品鍍膜"

data_processing:
  # filter out sentences that contain these words
  filter_words:
    - "請稍候專員為您服務"
    - "你正在回覆你粉絲專頁貼文"
    - "請告訴我們該如何為你提供協助"
    - "我是大大力小編"
    - "目前方案都在優惠中"
    - "小編是真人線上服務"
    - "大大力良品各分店地址"
    - "請問您是哪款車"
    - "全台21間門市"
    - "您好 我是店長小吳 很高興為您服務"
    - "【全台門市地址】"
    - "可以在接下來"
    - "請問您在哪個縣市"
    - ".com"
    - ".tw"
    - ".cn"
    - ".hk"
    - ".net"
    - ".org"
    - ".io"
    - ".ai"
  role_transfer: # if seen this sentence, then transfer the role to the user
    assistant_to_user:  
      - "回覆了 1 則"
    user_to_assistant:
  # filter out sentences that are too short
  # min_length: 5
  

# Path to save formatted output files (preserves original filenames)
input_formatted_path: data/formated_data/



# Features to extract from conversations
features:
  avg_latency: 
  initial_latency: 
    n_responses: 3
  user_reply_len: 
    min_len: 5
  message_count: 
  message_length: 
  response_time: 
  
  quality: 
  day_throughput: 
  hour_throughput: 
  ten_min_throughput: 
  time_features: 

# Targets to extract from conversations
targets:
  - "deal_make_or_not"
  - "sentiment_score" 
  - "user_engagement"



# Visualization configuration
visualization:
  output_directory: "./output/visualizations"
  plot_format: "png"
  dpi: 300
  figsize: [10, 6]
  style: "seaborn-v0_8-darkgrid"
  plot_types: ["distribution", "correlation", "time_series", "clusters"]
  top_features: 5
  correlation_method: "pearson" 
  target_metric: "all"

# Cleaning options
cleaning:
  enable_stopwords: true
  language_filter: "en"
  url_filter: true
  paragraph_filter: true
  deduplicate: true

# Formatting options
formatting:
  remove_punctuation: false
  clean_html: true
  fix_unicode: true